### ISSUE TITLE
Tile Markers for Ahkka Butterfly, Zebak Puzzle, Ahkka Puzzle, and Kephri Melee Trap

### ISSUE THREAD

**Issue by DatPeko** [TrevorMDev/tile-packs#16]
Just some convenient tiles for Tombs of Amascut and their corresponding rooms. 

Ahkka Butterfly
`[{"regionId":14676,"regionX":36,"regionY":32,"z":1,"color":"#FFFFFFFF"},{"regionId":14676,"regionX":36,"regionY":39,"z":1,"color":"#FFFFFFFF"},{"regionId":14676,"regionX":29,"regionY":39,"z":1,"color":"#FFFFFFFF"},{"regionId":14676,"regionX":29,"regionY":32,"z":1,"color":"#FFFFFFFF"},{"regionId":14676,"regionX":29,"regionY":31,"z":1,"color":"#FFFFFFFF"},{"regionId":14676,"regionX":29,"regionY":24,"z":1,"color":"#FFFFFFFF"},{"regionId":14676,"regionX":36,"regionY":31,"z":1,"color":"#FFFFFFFF"},{"regionId":14676,"regionX":36,"regionY":24,"z":1,"color":"#FFFFFFFF"},{"regionId":14676,"regionX":34,"regionY":22,"z":1,"color":"#968D8D8D"},{"regionId":14676,"regionX":31,"regionY":22,"z":1,"color":"#968D8D8D"},{"regionId":14676,"regionX":42,"regionY":30,"z":1,"color":"#968D8D8D"},{"regionId":14676,"regionX":42,"regionY":33,"z":1,"color":"#968D8D8D"},{"regionId":14676,"regionX":34,"regionY":41,"z":1,"color":"#968D8D8D"},{"regionId":14676,"regionX":31,"regionY":41,"z":1,"color":"#968D8D8D"},{"regionId":14676,"regionX":23,"regionY":33,"z":1,"color":"#968D8D8D"},{"regionId":14676,"regionX":23,"regionY":30,"z":1,"color":"#968D8D8D"},{"regionId":14676,"regionX":29,"regionY":28,"z":1,"color":"#32FFFFFF","label":"lol"},{"regionId":14676,"regionX":36,"regionY":28,"z":1,"color":"#32FFFFFF","label":"lol"},{"regionId":14676,"regionX":36,"regionY":35,"z":1,"color":"#32FFFFFF","label":"lol"},{"regionId":14676,"regionX":29,"regionY":35,"z":1,"color":"#32FFFFFF","label":"lol"},{"regionId":14676,"regionX":39,"regionY":27,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":39,"regionY":28,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":33,"regionY":28,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":33,"regionY":27,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":32,"regionY":28,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":32,"regionY":27,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":33,"regionY":35,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":33,"regionY":36,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":32,"regionY":36,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":32,"regionY":35,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":39,"regionY":36,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":39,"regionY":35,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":26,"regionY":36,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":26,"regionY":35,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":26,"regionY":28,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":26,"regionY":27,"z":1,"color":"#ABFFFFFF"},{"regionId":14676,"regionX":32,"regionY":32,"z":1,"color":"#FFFFFF00"},{"regionId":14676,"regionX":32,"regionY":31,"z":1,"color":"#FFFFFF00"},{"regionId":14676,"regionX":33,"regionY":31,"z":1,"color":"#FFFFFF00"},{"regionId":14676,"regionX":33,"regionY":32,"z":1,"color":"#FFFFFF00"}]`

Ahkka Puzzle
`[{"regionId":14674,"regionX":27,"regionY":40,"z":0,"color":"#FF00FFFF","label":"1"},{"regionId":14674,"regionX":36,"regionY":40,"z":0,"color":"#FF00FFFF","label":"1"},{"regionId":14674,"regionX":27,"regionY":32,"z":0,"color":"#FF00FFFF","label":"1, 2"},{"regionId":14674,"regionX":27,"regionY":28,"z":0,"color":"#FFFF2600","label":"2"},{"regionId":14674,"regionX":40,"regionY":28,"z":0,"color":"#FFFF2600","label":"2"},{"regionId":14674,"regionX":40,"regionY":32,"z":0,"color":"#FFFF2600","label":"2"},{"regionId":14674,"regionX":26,"regionY":32,"z":0,"color":"#FFFFE700","label":"3"},{"regionId":14674,"regionX":26,"regionY":24,"z":0,"color":"#FFFFE700","label":"3"},{"regionId":14674,"regionX":35,"regionY":24,"z":0,"color":"#FFFFE700","label":"3"},{"regionId":14674,"regionX":27,"regionY":41,"z":0,"color":"#FF797979"},{"regionId":14674,"regionX":41,"regionY":37,"z":0,"color":"#FF797979"},{"regionId":14674,"regionX":27,"regionY":23,"z":0,"color":"#FF797979"},{"regionId":14674,"regionX":25,"regionY":24,"z":0,"color":"#FF30FF00","label":"4"},{"regionId":14674,"regionX":39,"regionY":24,"z":0,"color":"#FF30FF00","label":"4"},{"regionId":14674,"regionX":24,"regionY":32,"z":0,"color":"#FF0013FF","label":"5"},{"regionId":14674,"regionX":24,"regionY":39,"z":0,"color":"#FF0013FF","label":"5"},{"regionId":14674,"regionX":35,"regionY":39,"z":0,"color":"#FF0013FF","label":"5"},{"regionId":14674,"regionX":25,"regionY":32,"z":0,"color":"#FF30FF00","label":"4, 6"},{"regionId":14674,"regionX":36,"regionY":39,"z":0,"color":"#FFFF00F1","label":"6"},{"regionId":14674,"regionX":25,"regionY":39,"z":0,"color":"#FFFF00F1","label":"6"}]`

Zebak Puzzle
`[{"regionId":15698,"regionX":37,"regionY":44,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":38,"regionY":44,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":27,"regionY":20,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":26,"regionY":20,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":27,"regionY":22,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":41,"regionY":20,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":40,"regionY":20,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":37,"regionY":42,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":23,"regionY":44,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":24,"regionY":44,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":27,"regionY":8,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":26,"regionY":8,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":40,"regionY":8,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":41,"regionY":8,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":41,"regionY":22,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":23,"regionY":56,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":24,"regionY":56,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":37,"regionY":56,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":38,"regionY":56,"z":0,"color":"#FF0026FF"},{"regionId":15698,"regionX":37,"regionY":46,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":46,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":45,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":45,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":42,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":43,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":43,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":48,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":48,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":50,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":50,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":52,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":52,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":54,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":54,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":57,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":57,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":55,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":55,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":53,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":53,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":51,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":51,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":49,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":49,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":47,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":47,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":45,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":45,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":46,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":46,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":48,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":48,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":50,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":50,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":52,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":52,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":54,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":54,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":57,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":57,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":55,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":55,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":53,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":53,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":51,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":51,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":49,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":49,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":47,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":47,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":22,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":21,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":21,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":19,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":19,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":17,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":17,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":15,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":15,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":13,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":13,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":11,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":9,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":9,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":11,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":7,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":7,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":10,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":10,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":12,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":12,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":14,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":14,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":16,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":16,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":18,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":18,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":22,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":21,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":21,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":19,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":19,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":17,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":17,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":15,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":15,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":14,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":14,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":18,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":18,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":16,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":16,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":12,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":12,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":10,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":10,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":13,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":13,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":11,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":11,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":9,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":9,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":7,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":7,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":43,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":43,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":27,"regionY":41,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":26,"regionY":41,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":42,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":42,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":40,"regionY":41,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":41,"regionY":41,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":37,"regionY":23,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":38,"regionY":23,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":23,"regionY":23,"z":0,"color":"#FFFFFF00"},{"regionId":15698,"regionX":24,"regionY":23,"z":0,"color":"#FFFFFF00"}]`

Kephri Melee Trap
`[{"regionId":14164,"regionX":36,"regionY":34,"z":0,"color":"#FFFFFF00","label":"Melee Trap 1"},{"regionId":14164,"regionX":36,"regionY":30,"z":0,"color":"#FFFFFF00","label":"Melee Trap 2"},{"regionId":14164,"regionX":39,"regionY":29,"z":0,"color":"#FFFFFF00","label":"Dung stack 1"},{"regionId":14164,"regionX":38,"regionY":29,"z":0,"color":"#FFFFFF00","label":"Dung stack 2"},{"regionId":14164,"regionX":37,"regionY":29,"z":0,"color":"#FFFFFF00","label":"Dung stack 3"},{"regionId":14164,"regionX":39,"regionY":35,"z":0,"color":"#FFFFFF00","label":"Dung stack 1"},{"regionId":14164,"regionX":38,"regionY":35,"z":0,"color":"#FFFFFF00","label":"Dung stack 2"},{"regionId":14164,"regionX":37,"regionY":35,"z":0,"color":"#FFFFFF00","label":"Dung stack 3"}]`

**Comment by TrevorMDev** [comment]
These will be included in the next release, thanks.
