### ISSUE TITLE
Double Trouble Toa markers

### ISSUE THREAD

**Issue by AntTham** [TrevorMDev/tile-packs#19]
Lord Hisoka's markers for raids 3 Ahka room from his yt vid.
https://www.youtube.com/watch?v=fYVd9jHkkWI&t=27s&ab_channel=LordHisoka

[{"regionId":14676,"regionX":48,"regionY":29,"z":1,"color":"#FF3F3F3F"},{"regionId":14676,"regionX":33,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":32,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":37,"regionY":32,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":37,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":36,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":33,"regionY":36,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":37,"regionY":36,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":39,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":39,"regionY":32,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":31,"regionY":26,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":26,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":27,"regionY":26,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":27,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":31,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":25,"regionY":30,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":25,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":27,"regionY":30,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":30,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":31,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":27,"regionY":32,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":25,"regionY":32,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":27,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":25,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":27,"regionY":36,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":36,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":31,"regionY":36,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":31,"regionY":38,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":38,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":33,"regionY":38,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":38,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":37,"regionY":38,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":39,"regionY":38,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":33,"regionY":40,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":40,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":41,"regionY":34,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":41,"regionY":32,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":30,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":37,"regionY":30,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":39,"regionY":30,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":41,"regionY":30,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":39,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":41,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":37,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":26,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":37,"regionY":26,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":39,"regionY":26,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":33,"regionY":26,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":31,"regionY":24,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":33,"regionY":24,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":35,"regionY":24,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":37,"regionY":24,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":27,"regionY":24,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":27,"regionY":38,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":31,"regionY":40,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":40,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":31,"regionY":30,"z":1,"color":"#FFFFDD00"},{"regionId":14676,"regionX":33,"regionY":30,"z":1,"color":"#FFFFDD00"},{"regionId":14676,"regionX":31,"regionY":32,"z":1,"color":"#FFFFDD00"},{"regionId":14676,"regionX":33,"regionY":32,"z":1,"color":"#FFFFDD00"},{"regionId":14676,"regionX":39,"regionY":36,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":33,"regionY":28,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":24,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":29,"regionY":32,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":25,"regionY":36,"z":1,"color":"#FF000000"},{"regionId":14676,"regionX":41,"regionY":36,"z":1,"color":"#FF000000"}]

**Comment by TrevorMDev** [comment]
This will be included in the next release. Thanks for the tiles.
