### ISSUE TITLE
Tile Pack: Guardians of the Rift (GOTR)

### ISSUE THREAD

**Issue by Nick2bad4u** [TrevorMDev/tile-packs#21]
[Link to RuneLite Tile Shower Webpage](https://runelite.net/tile/show/#W3sicmVnaW9uSWQiOjE0NDg0LCJyZWdpb25YIjo2LCJyZWdpb25ZIjoyNiwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6Ik1pbmUifSx7InJlZ2lvbklkIjoxNDQ4NCwicmVnaW9uWCI6MjEsInJlZ2lvblkiOjE2LCJ6IjowLCJjb2xvciI6IiNCQjAwRkYwMCIsImxhYmVsIjoiTWluZSJ9LHsicmVnaW9uSWQiOjE0NDg0LCJyZWdpb25YIjo5LCJyZWdpb25ZIjozMSwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IlBvcnRhbCJ9LHsicmVnaW9uSWQiOjE0NDg0LCJyZWdpb25YIjoyNCwicmVnaW9uWSI6MzEsInoiOjAsImNvbG9yIjoiI0JCMDBGRjAwIiwibGFiZWwiOiJDZWxsIn0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjI1LCJyZWdpb25ZIjoxNSwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IlJ1bmVzIn0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjM4LCJyZWdpb25ZIjozMSwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IkNlbGwifSx7InJlZ2lvbklkIjoxNDQ4NCwicmVnaW9uWCI6MTksInJlZ2lvblkiOjIxLCJ6IjowLCJjb2xvciI6IiNCQjAwRkYwMCIsImxhYmVsIjoiU1cifSx7InJlZ2lvbklkIjoxNDQ4NCwicmVnaW9uWCI6NDMsInJlZ2lvblkiOjMxLCJ6IjowLCJjb2xvciI6IiNCQjAwRkYwMCIsImxhYmVsIjoiRWFzdCJ9LHsicmVnaW9uSWQiOjE0NDg0LCJyZWdpb25YIjozMSwicmVnaW9uWSI6MzAsInoiOjAsImNvbG9yIjoiI0JCMDBGRjAwIiwibGFiZWwiOiJQb3dlciBVcCJ9LHsicmVnaW9uSWQiOjE0NDg0LCJyZWdpb25YIjo1MCwicmVnaW9uWSI6MzEsInoiOjAsImNvbG9yIjoiI0JCMDBGRjAwIiwibGFiZWwiOiJDbGltYiJ9LHsicmVnaW9uSWQiOjE0NDg0LCJyZWdpb25YIjo1MiwicmVnaW9uWSI6MzEsInoiOjAsImNvbG9yIjoiI0JCMDBGRjAwIiwibGFiZWwiOiJDbGltYiJ9LHsicmVnaW9uSWQiOjE0NDg0LCJyZWdpb25YIjozMSwicmVnaW9uWSI6MTUsInoiOjAsImNvbG9yIjoiI0JCMDBGRjAwIiwibGFiZWwiOiJTb3V0aCJ9LHsicmVnaW9uSWQiOjE0NDg0LCJyZWdpb25YIjo1NiwicmVnaW9uWSI6MjYsInoiOjAsImNvbG9yIjoiI0JCMDBGRjAwIiwibGFiZWwiOiJNaW5lIDE2MH4ifSx7InJlZ2lvbklkIjoxNDQ4NCwicmVnaW9uWCI6NiwicmVnaW9uWSI6MzcsInoiOjAsImNvbG9yIjoiI0JCMDBGRjAwIiwibGFiZWwiOiJNaW5lIn0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjQzLCJyZWdpb25ZIjoyMSwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IlNFIn0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjM0LCJyZWdpb25ZIjoxNiwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IkNlbGxzIn0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjM1LCJyZWdpb25ZIjoxNiwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IkNlbGxzIn0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjI3LCJyZWdpb25ZIjoxNSwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IkNyYWZ0In0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjI4LCJyZWdpb25ZIjoxNSwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IkNyYWZ0In0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjI3LCJyZWdpb25ZIjoxNCwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IkNyYWZ0In0seyJyZWdpb25JZCI6MTQ0ODQsInJlZ2lvblgiOjI4LCJyZWdpb25ZIjoxNCwieiI6MCwiY29sb3IiOiIjQkIwMEZGMDAiLCJsYWJlbCI6IkNyYWZ0In1d)
![image](https://user-images.githubusercontent.com/20943337/219885483-3b5ecd84-85ee-4c8a-b432-97bea2b55631.png)

Manual Screenshot: 
![image](https://user-images.githubusercontent.com/20943337/219885312-e6bac828-4a5d-4b76-b6ab-6bea170f5841.png)
https://i.gyazo.com/63f7deab47d82cd838ce1dfb6b4900be.jpg

Manual export: 
[{"regionId":14484,"regionX":6,"regionY":26,"z":0,"color":"#BB00FF00","label":"Mine"},{"regionId":14484,"regionX":21,"regionY":16,"z":0,"color":"#BB00FF00","label":"Mine"},{"regionId":14484,"regionX":9,"regionY":31,"z":0,"color":"#BB00FF00","label":"Portal"},{"regionId":14484,"regionX":24,"regionY":31,"z":0,"color":"#BB00FF00","label":"Cell"},{"regionId":14484,"regionX":25,"regionY":15,"z":0,"color":"#BB00FF00","label":"Runes"},{"regionId":14484,"regionX":38,"regionY":31,"z":0,"color":"#BB00FF00","label":"Cell"},{"regionId":14484,"regionX":19,"regionY":21,"z":0,"color":"#BB00FF00","label":"SW"},{"regionId":14484,"regionX":43,"regionY":31,"z":0,"color":"#BB00FF00","label":"East"},{"regionId":14484,"regionX":31,"regionY":30,"z":0,"color":"#BB00FF00","label":"Power Up"},{"regionId":14484,"regionX":50,"regionY":31,"z":0,"color":"#BB00FF00","label":"Climb"},{"regionId":14484,"regionX":52,"regionY":31,"z":0,"color":"#BB00FF00","label":"Climb"},{"regionId":14484,"regionX":31,"regionY":15,"z":0,"color":"#BB00FF00","label":"South"},{"regionId":14484,"regionX":56,"regionY":26,"z":0,"color":"#BB00FF00","label":"Mine 160~"},{"regionId":14484,"regionX":6,"regionY":37,"z":0,"color":"#BB00FF00","label":"Mine"},{"regionId":14484,"regionX":43,"regionY":21,"z":0,"color":"#BB00FF00","label":"SE"},{"regionId":14484,"regionX":34,"regionY":16,"z":0,"color":"#BB00FF00","label":"Cells"},{"regionId":14484,"regionX":35,"regionY":16,"z":0,"color":"#BB00FF00","label":"Cells"},{"regionId":14484,"regionX":27,"regionY":15,"z":0,"color":"#BB00FF00","label":"Craft"},{"regionId":14484,"regionX":28,"regionY":15,"z":0,"color":"#BB00FF00","label":"Craft"},{"regionId":14484,"regionX":27,"regionY":14,"z":0,"color":"#BB00FF00","label":"Craft"},{"regionId":14484,"regionX":28,"regionY":14,"z":0,"color":"#BB00FF00","label":"Craft"}]

**Comment by TrevorMDev** [comment]
This will be included in the next release, thanks.
