### ISSUE TITLE
Commander Zilyana Bowfa (Energy Efficient)

### ISSUE THREAD

**Issue by j-grady** [TrevorMDev/tile-packs#24]
Hi there! I just came across this plugin and definitely love the ability to have all ground markers grouped into separate packs!

Like the plugin description suggested, creating a new issue for a new tile pack! Here's a slightly different Zilyana Bowfa ground marker set that **conserves energy** so you don't need stamina potions:

Ground markers:
```
[{"regionId":11602,"regionX":26,"regionY":10,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":26,"regionY":17,"z":0,"color":"#FFFFFF00"},
{"regionId":11602,"regionX":26,"regionY":13,"z":0,"color":"#FFFFFF00"},
{"regionId":11602,"regionX":19,"regionY":10,"z":0,"color":"#FFFFFF00"},
{"regionId":11602,"regionX":27,"regionY":21,"z":0,"color":"#FF00FF00"},
{"regionId":11602,"regionX":26,"regionY":15,"z":0,"color":"#FF00FF00"},
{"regionId":11602,"regionX":26,"regionY":18,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":26,"regionY":14,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":20,"regionY":10,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":15,"regionY":10,"z":0,"color":"#FFFFFF00"},
{"regionId":11602,"regionX":11,"regionY":14,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":9,"regionY":19,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":9,"regionY":24,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":11,"regionY":26,"z":0,"color":"#FFFFFF00"},
{"regionId":11602,"regionX":15,"regionY":27,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":21,"regionY":26,"z":0,"color":"#FFFFFF00"},
{"regionId":11602,"regionX":24,"regionY":24,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":16,"regionY":10,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":20,"regionY":26,"z":0,"color":"#FFFF0000"},
{"regionId":11602,"regionX":27,"regionY":24,"z":0,"color":"#FF0000FF"},
{"regionId":11602,"regionX":18,"regionY":22,"z":0,"color":"#FF000000"},
{"regionId":11602,"regionX":17,"regionY":22,"z":0,"color":"#FF000000"},
{"regionId":11602,"regionX":17,"regionY":21,"z":0,"color":"#FF000000"},
{"regionId":11602,"regionX":18,"regionY":21,"z":0,"color":"#FF000000"}]
```

Map: [RuneLite Tile markers](https://runelite.net/tile/show/#W3sicmVnaW9uSWQiOjExNjAyLCJyZWdpb25YIjoyNiwicmVnaW9uWSI6MTAsInoiOjAsImNvbG9yIjoiI0ZGRkYwMDAwIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjI2LCJyZWdpb25ZIjoxNywieiI6MCwiY29sb3IiOiIjRkZGRkZGMDAifSx7InJlZ2lvbklkIjoxMTYwMiwicmVnaW9uWCI6MjYsInJlZ2lvblkiOjEzLCJ6IjowLCJjb2xvciI6IiNGRkZGRkYwMCJ9LHsicmVnaW9uSWQiOjExNjAyLCJyZWdpb25YIjoxOSwicmVnaW9uWSI6MTAsInoiOjAsImNvbG9yIjoiI0ZGRkZGRjAwIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjI3LCJyZWdpb25ZIjoyMSwieiI6MCwiY29sb3IiOiIjRkYwMEZGMDAifSx7InJlZ2lvbklkIjoxMTYwMiwicmVnaW9uWCI6MjYsInJlZ2lvblkiOjE1LCJ6IjowLCJjb2xvciI6IiNGRjAwRkYwMCJ9LHsicmVnaW9uSWQiOjExNjAyLCJyZWdpb25YIjoyNiwicmVnaW9uWSI6MTgsInoiOjAsImNvbG9yIjoiI0ZGRkYwMDAwIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjI2LCJyZWdpb25ZIjoxNCwieiI6MCwiY29sb3IiOiIjRkZGRjAwMDAifSx7InJlZ2lvbklkIjoxMTYwMiwicmVnaW9uWCI6MjAsInJlZ2lvblkiOjEwLCJ6IjowLCJjb2xvciI6IiNGRkZGMDAwMCJ9LHsicmVnaW9uSWQiOjExNjAyLCJyZWdpb25YIjoxNSwicmVnaW9uWSI6MTAsInoiOjAsImNvbG9yIjoiI0ZGRkZGRjAwIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjExLCJyZWdpb25ZIjoxNCwieiI6MCwiY29sb3IiOiIjRkZGRjAwMDAifSx7InJlZ2lvbklkIjoxMTYwMiwicmVnaW9uWCI6OSwicmVnaW9uWSI6MTksInoiOjAsImNvbG9yIjoiI0ZGRkYwMDAwIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjksInJlZ2lvblkiOjI0LCJ6IjowLCJjb2xvciI6IiNGRkZGMDAwMCJ9LHsicmVnaW9uSWQiOjExNjAyLCJyZWdpb25YIjoxMSwicmVnaW9uWSI6MjYsInoiOjAsImNvbG9yIjoiI0ZGRkZGRjAwIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjE1LCJyZWdpb25ZIjoyNywieiI6MCwiY29sb3IiOiIjRkZGRjAwMDAifSx7InJlZ2lvbklkIjoxMTYwMiwicmVnaW9uWCI6MjEsInJlZ2lvblkiOjI2LCJ6IjowLCJjb2xvciI6IiNGRkZGRkYwMCJ9LHsicmVnaW9uSWQiOjExNjAyLCJyZWdpb25YIjoyNCwicmVnaW9uWSI6MjQsInoiOjAsImNvbG9yIjoiI0ZGRkYwMDAwIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjE2LCJyZWdpb25ZIjoxMCwieiI6MCwiY29sb3IiOiIjRkZGRjAwMDAifSx7InJlZ2lvbklkIjoxMTYwMiwicmVnaW9uWCI6MjAsInJlZ2lvblkiOjI2LCJ6IjowLCJjb2xvciI6IiNGRkZGMDAwMCJ9LHsicmVnaW9uSWQiOjExNjAyLCJyZWdpb25YIjoyNywicmVnaW9uWSI6MjQsInoiOjAsImNvbG9yIjoiI0ZGMDAwMEZGIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjE4LCJyZWdpb25ZIjoyMiwieiI6MCwiY29sb3IiOiIjRkYwMDAwMDAifSx7InJlZ2lvbklkIjoxMTYwMiwicmVnaW9uWCI6MTcsInJlZ2lvblkiOjIyLCJ6IjowLCJjb2xvciI6IiNGRjAwMDAwMCJ9LHsicmVnaW9uSWQiOjExNjAyLCJyZWdpb25YIjoxNywicmVnaW9uWSI6MjEsInoiOjAsImNvbG9yIjoiI0ZGMDAwMDAwIn0seyJyZWdpb25JZCI6MTE2MDIsInJlZ2lvblgiOjE4LCJyZWdpb25ZIjoyMSwieiI6MCwiY29sb3IiOiIjRkYwMDAwMDAifV0=)

YouTube video (GeChallengeM): https://www.youtube.com/watch?v=EaqZaAw0DHk

Please feel free to let me know if you have any questions.

**Comment by j-grady** [comment]
I just realized we can add custom packs at the bottom of the menu, so I manually added this for the time being. 🙂

**Comment by TrevorMDev** [comment]
Yes that feature just went live, I will still add this pack to the core plugin in the next update.

**Comment by TrevorMDev** [comment]
This will be added in the next release soon.
