### ISSUE TITLE
Add Kril markers to plugin

### ISSUE THREAD

**Issue by Brickfingers** [TrevorMDev/tile-packs#26]
Hey, are you still maintaining and adding default packs to this plugin?

Can you add the zammy 5:0 https://www.youtube.com/watch?v=DJoqC65UyhE
[{"regionId":11603,"regionX":48,"regionY":9,"z":2,"color":"#FF6B6BFF","label":"x"},{"regionId":11603,"regionX":38,"regionY":13,"z":2,"color":"#FF6B6BFF","label":"1"},{"regionId":11603,"regionX":54,"regionY":13,"z":2,"color":"#FF6B6BFF","label":"3"},{"regionId":11603,"regionX":50,"regionY":6,"z":2,"color":"#FF6B6BFF","label":"4"},{"regionId":11603,"regionX":42,"regionY":9,"z":2,"color":"#FF6B6BFF","label":"5"}]

and 8:0 https://www.youtube.com/watch?v=NoOSS6Ed240&t=223s
[{"regionId":11603,"regionX":42,"regionY":9,"z":2,"color":"#FF6B6BFF"},{"regionId":11603,"regionX":38,"regionY":6,"z":2,"color":"#FF6B6BFF"},{"regionId":11603,"regionX":38,"regionY":12,"z":2,"color":"#FF6B6BFF"},{"regionId":11603,"regionX":46,"regionY":9,"z":2,"color":"#FF6B6BFF"},{"regionId":11603,"regionX":46,"regionY":16,"z":2,"color":"#FF6B6BFF"},{"regionId":11603,"regionX":51,"regionY":16,"z":2,"color":"#FF6B6BFF"},{"regionId":11603,"regionX":55,"regionY":15,"z":2,"color":"#FF6B6BFF"},{"regionId":11603,"regionX":52,"regionY":9,"z":2,"color":"#FF6B6BFF"},{"regionId":11603,"regionX":47,"regionY":18,"z":2,"color":"#14FFDD00","label":"cannon"},{"regionId":11603,"regionX":54,"regionY":16,"z":2,"color":"#14FFDD00"},{"regionId":11603,"regionX":43,"regionY":9,"z":2,"color":"#14FFDD00"},{"regionId":11603,"regionX":39,"regionY":11,"z":2,"color":"#14FFDD00"}]

thanks in advance

**Comment by TrevorMDev** [comment]
This will be added in the next release soon.
