### ISSUE TITLE
Default Pack Deletion

### ISSUE THREAD

**Issue by Brown410** [TrevorMDev/tile-packs#27]
It would be amazing to be able to delete default packs in the plug-in and to be able to start from a clean slate to remove some clutter. Or maybe add "favorites" so that packs that you want to use will be at the top.

**Comment by TrevorMDev** [comment]
I don't want to allow deletion of default packs, because a big purpose of the plugin is to have these presets. I do like the idea of a favorite button though to add some custom sorting.

**Comment by TrevorMDev** [comment]
The plugin now has the ability to hide the default packs, which is as close to deletion as it is going to get.
