### ISSUE TITLE
Add a way to update custom packs

### ISSUE THREAD

**Issue by Shadowclysm** [TrevorMDev/tile-packs#29]
It is very difficult to make changes to custom packs.
There should be a button on each custom pack to load its name and tile info into the existing new custom pack text fields and give "Add Pack" button a confirmation dialog to override the existing custom pack with the same name.

**Comment by TrevorMDev** [comment]
If this were to be implemented, I would do it with a pop up that contains the pack text and let it be saved from there.

I plan to add an export functionality for all packs, which should make this easier to deal with also.

**Comment by Shadowclysm** [comment]
I see this was added recently 👍
